### ISSUE TITLE
tests fail

### ISSUE THREAD

**Issue by dvohra** [keedio/flume-ng-sql-source#22]
The tests fail with mvn package:
## T E S T S

Running org.keedio.flume.source.SQLSourceHelperTest
log4j:WARN No appenders could be found for logger (org.keedio.flume.source.SQLSo
urceHelper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more in
fo.
Tests run: 20, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 1.03 sec <<< FA
ILURE! - in org.keedio.flume.source.SQLSourceHelperTest
checkStatusFileCorrectlyUpdated(org.keedio.flume.source.SQLSourceHelperTest)  Ti
me elapsed: 0.499 sec  <<< FAILURE!
java.lang.AssertionError: expected:<10> but was:<0>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:834)
        at org.junit.Assert.assertEquals(Assert.java:645)
        at org.junit.Assert.assertEquals(Assert.java:631)
        at org.keedio.flume.source.SQLSourceHelperTest.checkStatusFileCorrectlyU
pdated(SQLSourceHelperTest.java:170)

getCustomQuery(org.keedio.flume.source.SQLSourceHelperTest)  Time elapsed: 0 sec
  <<< ERROR!
org.apache.flume.conf.ConfigurationException: status.column.name property not se
t
        at org.keedio.flume.source.SQLSourceHelper.checkMandatoryProperties(SQLS
ourceHelper.java:310)
        at org.keedio.flume.source.SQLSourceHelper.<init>(SQLSourceHelper.java:9
7)
        at org.keedio.flume.source.SQLSourceHelperTest.getCustomQuery(SQLSourceH
elperTest.java:239)

Results :

Failed tests:
  SQLSourceHelperTest.checkStatusFileCorrectlyUpdated:170 expected:<10> but was:
<0>
Tests in error:
  SQLSourceHelperTest.getCustomQuery:239 ╗ Configuration status.column.name prop
...

Tests run: 20, Failures: 1, Errors: 1, Skipped: 0

**Comment by mvalleavila** [comment]
Not reproduced in version 1.4.3
