### ISSUE TITLE
delimiter of the incoming data from mysql

### ISSUE THREAD

**Issue by simran-k** [keedio/flume-ng-sql-source#31]
I see that the data is delimited by comma. I do have comma in my values as well and that seems to break the format.

Is there a way I can use some other delimiter ? I am using hive as a sink and that requires me to specify the delimiter of my incoming data.

This:

serializer.delimiter	,	(Type: string) The field delimiter in the incoming data. To use special characters, surround them with double quotes like “\t”.

It also needs me to make sure that this delimiter is not in the data values

**Comment by lufeng1102** [comment]
Hi simran-k, I have also meet this issue. Do you already solve this issue?

**Comment by lufeng1102** [comment]
I have add a patch for this issue. Feel free to review it. https://github.com/keedio/flume-ng-sql-source/pull/32

**Comment by mvalleavila** [comment]
Thanks @lufeng1102 !!
