### ISSUE TITLE
Could not open connection from Postgresql

### ISSUE THREAD

**Issue by ekapramudita** [keedio/flume-ng-sql-source#36]
Hi, I got some problem :

there are :

org.hibernate.exception.GenericJDBCException: Could not open connection

and

java.sql.SQLException: No suitable driver
        at java.sql.DriverManager.getDriver(DriverManager.java:278)

anyone can help?

**Comment by mvalleavila** [comment]
Hello,

Are you including the postgresSql Driver in your flume classpath?
(https://github.com/keedio/flume-ng-sql-source#specific-installation-by-database-engine)

**Comment by ekapramudita** [comment]
Hi mvalleavila,

I missed that part.
Now my connection work normally.

Thank you for help.

**Comment by mvalleavila** [comment]
No worries!
