### ISSUE TITLE
org.apache.flume.conf.ConfigurationException: hibernate.connection.url property not set

### ISSUE THREAD

**Issue by starbow727** [keedio/flume-ng-sql-source#37]
The following is no problem to write, I write their own mistakes
##name
agent.channels = ch1
agent.sinks = HDFS
agent.sources =sqlSource
##channel
agent.channels.ch1.type = memory
agent.sources.sqlSource.channels = ch1
##source
agent.sources.sqlSource.type = org.keedio.flume.source.SQLSource
agent.sources.sqlSource.hibernate.connection.url = jdbc:mysql://192.168.222.122:3306/bigdata_lots
agent.sources.sqlSource.hibernate.connection.user = bigots
agent.sources.sqlSource.hibernate.connection.password = Bitts.2017
agent.sources.sqlSource.hibernate.connection.autocommit = true
agent.sources.sqlSource.hibernate.dialect = org.hibernate.dialect.MySQLDialect
agent.sources.sqlSource.hibernate.connection.driver_class = com.mysql.jdbc.Driver
agent.sources.sqlSource.table = ecological_company
agent.sources.sqlSource.columns.to.select = *
agent.sources.sqlSource.run.query.delay=10000
agent.sources.sqlSource.status.file.path = /var/lib/flume
agent.sources.sqlSource.status.file.name = sqlSource.status
agent.sources.sqlSource.hibernate.connection.provider_class = org.hibernate.connection.C3P0ConnectionProvider
agent.sources.sqlSource.hibernate.c3p0.min_size=1
agent.sources.sqlSource.hibernate.c3p0.max_size=10
##sink
agent.sinks.HDFS.channel = ch1
agent.sinks.HDFS.type = hdfs
agent.sinks.HDFS.hdfs.path = hdfs://nameservice1/flume/mysql
agent.sinks.HDFS.hdfs.fileType = DataStream
agent.sinks.HDFS.hdfs.writeFormat = Text
agent.sinks.HDFS.hdfs.rollSize = 268435456
agent.sinks.HDFS.hdfs.rollInterval = 0

**Comment by mvalleavila** [comment]
Hello,

the configuration seems to be correct,
can you attach the complete stack trace?

**Comment by starbow727** [comment]
Yes my question has been resolved, there is no problem above.
