### ISSUE TITLE
Already put postgreSQL Driver, but still got error java.sql.SQLException: No suitable driver

### ISSUE THREAD

**Issue by ekapramudita** [keedio/flume-ng-sql-source#46]
Hi all,

I'm already put postgreSQL driver into flume-ng/plugins.d/sql-source/libext path.
But I still got error java.sql.SQLException: No suitable driver.

The postgreSQL driver was downloaded from this link 
https://jdbc.postgresql.org/download/postgresql-42.1.4.jar

and my postgreSQL version is 9.6.5 

any suggestion?

**Comment by mvalleavila** [comment]
Hello @ekapramudita ,

the path flume-ng/plugins.d/sql-source/libext is correct (and helps my to find a typo in deployment instructions in the README file :) )

You can look at the flume process java classpath, to check if the driver is being correctly added to it.
with 
'''
ps fax | grep flume
'''

Another possible check is to ensure that connection URL is in form jdbc:postgresql://host:port/database

Hope it helps

**Comment by ekapramudita** [comment]
Hi,

I try to execute that command, and the result is 
`3007 pts/0    S+     0:00              \_ grep --color=auto flume`
