### ISSUE TITLE
Kafka topic - Key and partition through Flume

### ISSUE THREAD

**Issue by josemasuarez** [keedio/flume-ng-sql-source#47]
Hi,

When I get the data from Oracle in my case, I have to send this data with a specific key and partition to Kafka. Is there any way to specify through flume.conf?

Thanks in advance
Regards.

**Comment by jucaf** [comment]
It's a configuration related to flume kafka sink, not the source. Maybe
also you need to set some interceptors.

**Comment by lazaromedina** [comment]
As jucaf said, you issue is more related to flume-sink than to flume-source component.
Check for [Apache Flume Kafka sink](https://flume.apache.org/FlumeUserGuide.html#kafka-sink)
Best, Luis.
