### ISSUE TITLE
the source can output json format ?

### ISSUE THREAD

**Issue by yxydde** [keedio/flume-ng-sql-source#55]

**Comment by lazaromedina** [comment]
Hi yxydde,
not actually, may be you can try out an interceptor to intercept message(one record with columns values) before arriving to channel and build a json with some external library.

best

**Comment by yxydde** [comment]
thanks , I have done !

**Comment by lazaromedina** [comment]
thank you yxydde, i'm closing issue, please reopen or open a new one if we can help you.
best
